#
# Progetto: PuzzleSolver - Genertor
# Autore: Giacomo Cusinato
# Data creazione: 2014/07/12
#

progetto: Init.class Generator.class Block.class

Init.class: Init.java
	javac Init.java

Generator.class: Generator.java
	javac Generator.java

Block.class: Block.java
	javac Block.java

clean: 
	rm -f *.class
