#
# Progetto: PuzzleSolver - Genertor
# Autore: Giacomo Cusinato
# Data creazione: 2014/07/12
#

progetto: src/Init.class src/Generator.class src/Block.class

Init.class: src/Init.java
	javac src/Init.java

Generator.class: src/Generator.java
	javac src/Generator.java

Block.class: src/Block.java
	javac src/Block.java

clean: 
	rm -f src/*.class
