progetto : PuzzleSolver.class IOHelper.class Block.class

PuzzleSolver.class : PuzzleSolver.java
	javac PuzzleSolver.java

IOHelper.class : IOHelper.java
	javac IOHelper.java

Block.class : Block.java
	javac Block.java

clean :
	rm -f *.class