progetto: client/PuzzleSolverClient.class client/IOHelper.class server/Block.java server/PuzzleSolverServer.class server/PuzzleThread.class

client/PuzzleSolverClient.class: client/PuzzleSolverClient.java
	cd ./client/ && javac PuzzleSolverClient.java

client/IOHelper.class: client/IOHelper.java
	cd ./client/ && javac IOHelper.java

server/PuzzleSolverServer.class: server/PuzzleSolverServer.java
	cd ./server/ && javac PuzzleSolverServer.java

server/Block.class: server/Block.java
	cd ./server/ && javac Block.java

server/PuzzleThread.class: server/PuzzleThread.java
	cd ./server/ && javac PuzzleThread.java

clean:
	rm -f server/*.class
	rm -f client/*.class